/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio8;

import javax.swing.JOptionPane;

/**
 *
 * @author Nathan
 */
public class X0 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(X0.class.getName());
    private String turno;
    private UsuarioJugador jugadorX;
    private UsuarioJugador jugadorO;

    /**
     * Creates new form X0
     */
    public X0() {
        initComponents();
        setLocationRelativeTo(this);
        this.turno = "X";
        this.jugadorX = new UsuarioJugador("PlayerX", 0);
        this.jugadorO = new UsuarioJugador("PlayerO", 0);
        inicializarJuego();

    }

    public X0(UsuarioJugador jugadorX, UsuarioJugador jugadorO) {
        this.turno = "X";
        this.jugadorX = jugadorX;
        this.jugadorO = jugadorO;
    }

    private void inicializarJuego() {

        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");

        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);

        turno = "X";
        actualizarInfoJuego();
    }

   private void actualizarInfoJuego() {
        if (lblPuntosO != null) {
            lblPuntosO.setText("Turno: " + turno);
        }
        if (lblPuntosO != null) {
            lblPuntosO.setText("Puntos " + jugadorX.getUsuario() + ": " + jugadorX.getPuntos());
        }
        if (lblPuntosO != null) {
            lblPuntosO.setText("Puntos " + jugadorO.getUsuario() + ": " + jugadorO.getPuntos());
        }
    
    private boolean verificarGanador() {
        String b1 = jButton1.getText();
        String b2 = jButton2.getText();
        String b3 = jButton3.getText();
        String b4 = jButton4.getText();
        String b5 = jButton5.getText();
        String b6 = jButton6.getText();
        String b7 = jButton7.getText();
        String b8 = jButton8.getText();
        String b9 = jButton9.getText();

        // Check rows
        if (!b1.isEmpty() && b1.equals(b2) && b1.equals(b3)) return true;
        if (!b4.isEmpty() && b4.equals(b5) && b4.equals(b6)) return true;
        if (!b7.isEmpty() && b7.equals(b8) && b7.equals(b9)) return true;

        // Check columns
        if (!b1.isEmpty() && b1.equals(b4) && b1.equals(b7)) return true;
        if (!b2.isEmpty() && b2.equals(b5) && b2.equals(b8)) return true;
        if (!b3.isEmpty() && b3.equals(b6) && b3.equals(b9)) return true;

        // Check diagonals
        if (!b1.isEmpty() && b1.equals(b5) && b1.equals(b9)) return true;
        if (!b3.isEmpty() && b3.equals(b5) && b3.equals(b7)) return true;

        return false;
    }
    
    private void deshabilitarTodosLosBotones() {
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
    }

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "¿Estás seguro que quieres regresar al menú principal? Se perderá el progreso del juego.", "Regresar", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            new Menu_Principal().setVisible(true);
            this.dispose();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        lblPuntosO = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        lblTurno1 = new javax.swing.JLabel();
        lblPuntosX1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));
        getContentPane().setLayout(null);

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 50));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 160, 500, 20);

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 50));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 330, 500, 20);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 50));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 0, 20, 510);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 50));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 0, 20, 510);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setBorder(null);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 40, 100, 100);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setBorder(null);
        jButton2.setOpaque(true);
        jPanel1.add(jButton2);
        jButton2.setBounds(190, 40, 100, 100);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setBorder(null);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(360, 40, 100, 100);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setBorder(null);
        jButton4.setOpaque(true);
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 210, 100, 100);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setBorder(null);
        jButton5.setOpaque(true);
        jPanel1.add(jButton5);
        jButton5.setBounds(190, 210, 100, 100);

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setBorder(null);
        jButton6.setOpaque(true);
        jPanel1.add(jButton6);
        jButton6.setBounds(370, 210, 100, 100);

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setBorder(null);
        jButton7.setOpaque(true);
        jPanel1.add(jButton7);
        jButton7.setBounds(20, 380, 100, 100);

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setBorder(null);
        jButton8.setOpaque(true);
        jPanel1.add(jButton8);
        jButton8.setBounds(190, 380, 100, 100);

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setBorder(null);
        jButton9.setOpaque(true);
        jPanel1.add(jButton9);
        jButton9.setBounds(370, 380, 100, 100);

        lblPuntosO.setBackground(new java.awt.Color(255, 255, 255));
        lblPuntosO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblPuntosO);
        lblPuntosO.setBounds(570, 210, 160, 50);

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio8/icons8-salida-32.png"))); // NOI18N
        volver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        volver.setOpaque(true);
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver);
        volver.setBounds(650, 280, 70, 40);

        lblTurno1.setBackground(new java.awt.Color(255, 255, 255));
        lblTurno1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblTurno1);
        lblTurno1.setBounds(570, 80, 160, 50);

        lblPuntosX1.setBackground(new java.awt.Color(255, 255, 255));
        lblPuntosX1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblPuntosX1);
        lblPuntosX1.setBounds(570, 150, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -6, 750, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        new Menu_Principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new X0().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPuntosO;
    private javax.swing.JLabel lblPuntosX1;
    private javax.swing.JLabel lblTurno1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
